// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"

	"github.com/kapu/hololive-kakao-bot-go/internal/bot"
	"github.com/kapu/hololive-kakao-bot-go/internal/config"
	"github.com/kapu/hololive-kakao-bot-go/internal/service/member"

	"log/slog"
)

// Injectors from wire.go:

// InitializeBotDependencies - Wire가 의존성 그래프를 분석하여 생성 코드 생성
// wire gen 명령으로 wire_gen.go 파일이 자동 생성됨
func InitializeBotDependencies(ctx context.Context, cfg *config.Config, logger *slog.Logger) (*bot.Dependencies, func(), error) {
	valkeyMQConfig := ProvideValkeyMQConfig(cfg)
	irisClient := ProvideIrisClient(valkeyMQConfig, logger)
	messageStack := ProvideMessageStack(cfg)
	valkeyConfig := ProvideValkeyConfig(cfg)
	cacheResources, cleanup, err := ProvideCacheResources(valkeyConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	cacheService := ProvideCacheService(cacheResources)
	postgresConfig := ProvidePostgresConfig(cfg)
	databaseResources, cleanup2, err := ProvideDatabaseResources(postgresConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	postgresService := ProvidePostgresService(databaseResources)
	memberRepository := ProvideMemberRepository(postgresService, logger)
	memberCache, err := ProvideMemberCache(ctx, memberRepository, cacheService, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := ProvideHolodexAPIKeys(cfg)
	memberServiceAdapter := ProvideMemberServiceAdapter(memberCache)
	scraperService := ProvideScraperService(cacheService, memberServiceAdapter, logger)
	holodexService, err := ProvideHolodexService(v, cacheService, scraperService, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	profileService, err := ProvideProfileService(ctx, cacheService, memberServiceAdapter, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	alarmService := ProvideAlarmService(cfg, cacheService, holodexService, logger)
	memberDataProvider := ProvideMembersData(memberServiceAdapter)
	memberMatcher := ProvideMemberMatcher(ctx, memberDataProvider, cacheService, holodexService, logger)
	youTubeStatsRepository := ProvideYouTubeStatsRepository(postgresService, logger)
	youTubeStack := ProvideYouTubeStack(ctx, cfg, cacheService, memberServiceAdapter, youTubeStatsRepository, logger)
	activityLogger := ProvideActivityLogger(cfg, logger)
	settingsService := ProvideSettingsService(logger)
	aclService, err := ProvideACLService(cfg, postgresService, cacheService, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dependencies := ProvideBotDependencies(cfg, logger, irisClient, messageStack, cacheService, postgresService, memberRepository, memberCache, holodexService, profileService, alarmService, memberMatcher, memberDataProvider, youTubeStack, activityLogger, settingsService, aclService)
	return dependencies, func() {
		cleanup2()
		cleanup()
	}, nil
}

// InitializeBotRuntime - cmd/bot 런타임 (Bot + MQ + Admin API 구성요소)
func InitializeBotRuntime(ctx context.Context, cfg *config.Config, logger *slog.Logger) (*BotRuntime, func(), error) {
	valkeyMQConfig := ProvideValkeyMQConfig(cfg)
	irisClient := ProvideIrisClient(valkeyMQConfig, logger)
	messageStack := ProvideMessageStack(cfg)
	valkeyConfig := ProvideValkeyConfig(cfg)
	cacheResources, cleanup, err := ProvideCacheResources(valkeyConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	cacheService := ProvideCacheService(cacheResources)
	postgresConfig := ProvidePostgresConfig(cfg)
	databaseResources, cleanup2, err := ProvideDatabaseResources(postgresConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	postgresService := ProvidePostgresService(databaseResources)
	memberRepository := ProvideMemberRepository(postgresService, logger)
	memberCache, err := ProvideMemberCache(ctx, memberRepository, cacheService, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := ProvideHolodexAPIKeys(cfg)
	memberServiceAdapter := ProvideMemberServiceAdapter(memberCache)
	scraperService := ProvideScraperService(cacheService, memberServiceAdapter, logger)
	holodexService, err := ProvideHolodexService(v, cacheService, scraperService, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	profileService, err := ProvideProfileService(ctx, cacheService, memberServiceAdapter, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	alarmService := ProvideAlarmService(cfg, cacheService, holodexService, logger)
	memberDataProvider := ProvideMembersData(memberServiceAdapter)
	memberMatcher := ProvideMemberMatcher(ctx, memberDataProvider, cacheService, holodexService, logger)
	youTubeStatsRepository := ProvideYouTubeStatsRepository(postgresService, logger)
	youTubeStack := ProvideYouTubeStack(ctx, cfg, cacheService, memberServiceAdapter, youTubeStatsRepository, logger)
	activityLogger := ProvideActivityLogger(cfg, logger)
	settingsService := ProvideSettingsService(logger)
	aclService, err := ProvideACLService(cfg, postgresService, cacheService, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dependencies := ProvideBotDependencies(cfg, logger, irisClient, messageStack, cacheService, postgresService, memberRepository, memberCache, holodexService, profileService, alarmService, memberMatcher, memberDataProvider, youTubeStack, activityLogger, settingsService, aclService)
	botBot, err := ProvideBot(dependencies)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	valkeyMQConsumer, err := ProvideValkeyMQConsumer(valkeyMQConfig, logger, botBot, cacheService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	youTubeScheduler := ProvideYouTubeScheduler(dependencies)
	youTubeService := ProvideYouTubeService(youTubeStack)
	valkeySessionStore := ProvideSessionStore(cacheService, logger)
	loginRateLimiter := ProvideLoginRateLimiter()
	securityConfig := ProvideSecurityConfig(cfg)
	adminCredentials := ProvideAdminCredentials(cfg)
	adminHandler := ProvideAdminHandler(memberRepository, memberCache, cacheService, alarmService, holodexService, youTubeService, activityLogger, settingsService, aclService, cfg, valkeySessionStore, loginRateLimiter, securityConfig, adminCredentials, logger)
	v2, err := ProvideAdminAllowedCIDRs(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	watchdogProxyHandler := ProvideWatchdogProxyHandler(cfg, logger, activityLogger)
	engine, err := ProvideAdminRouter(logger, adminHandler, watchdogProxyHandler, valkeySessionStore, securityConfig, v2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	string2 := ProvideAdminAddr(cfg)
	server := ProvideAdminServer(string2, engine)
	botRuntime := &BotRuntime{
		Config:            cfg,
		Logger:            logger,
		Bot:               botBot,
		MQConsumer:        valkeyMQConsumer,
		Scheduler:         youTubeScheduler,
		AdminHandler:      adminHandler,
		Sessions:          valkeySessionStore,
		SecurityConfig:    securityConfig,
		AdminAllowedCIDRs: v2,
		AdminRouter:       engine,
		AdminAddr:         string2,
		AdminServer:       server,
	}
	return botRuntime, func() {
		cleanup2()
		cleanup()
	}, nil
}

// InitializeWarmMemberCache - cmd/tools/warm_member_cache 전용
func InitializeWarmMemberCache(ctx context.Context, cfg *config.Config, logger *slog.Logger) (*member.Cache, func(), error) {
	postgresConfig := ProvidePostgresConfig(cfg)
	databaseResources, cleanup, err := ProvideDatabaseResources(postgresConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	postgresService := ProvidePostgresService(databaseResources)
	memberRepository := ProvideMemberRepository(postgresService, logger)
	valkeyConfig := ProvideValkeyConfig(cfg)
	cacheResources, cleanup2, err := ProvideCacheResources(valkeyConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacheService := ProvideCacheService(cacheResources)
	memberCache, err := ProvideMemberCache(ctx, memberRepository, cacheService, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return memberCache, func() {
		cleanup2()
		cleanup()
	}, nil
}

// InitializeDBIntegrationRuntime - cmd/test_db_integration 전용
func InitializeDBIntegrationRuntime(ctx context.Context, pgCfg config.PostgresConfig, logger *slog.Logger) (*DBIntegrationRuntime, func(), error) {
	databaseResources, cleanup, err := ProvideDatabaseResources(pgCfg, logger)
	if err != nil {
		return nil, nil, err
	}
	postgresService := ProvidePostgresService(databaseResources)
	memberRepository := ProvideMemberRepository(postgresService, logger)
	memberCache, err := ProvideMemberCacheWithoutValkey(ctx, memberRepository, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	memberServiceAdapter := ProvideMemberServiceAdapter(memberCache)
	dbIntegrationRuntime := &DBIntegrationRuntime{
		Logger:        logger,
		Repository:    memberRepository,
		Cache:         memberCache,
		MemberAdapter: memberServiceAdapter,
	}
	return dbIntegrationRuntime, func() {
		cleanup()
	}, nil
}

// InitializeFetchProfilesRuntime - cmd/tools/fetch_profiles 전용
func InitializeFetchProfilesRuntime(ctx context.Context) (*FetchProfilesRuntime, func(), error) {
	logger, cleanup, err := ProvideFetchProfilesLogger()
	if err != nil {
		return nil, nil, err
	}
	client := ProvideFetchProfilesHTTPClient()
	fetchProfilesRuntime := &FetchProfilesRuntime{
		Logger:     logger,
		HTTPClient: client,
	}
	return fetchProfilesRuntime, func() {
		cleanup()
	}, nil
}
