// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/park285/llm-kakao-bots/game-bot-go/internal/common/bootstrap"
	"github.com/park285/llm-kakao-bots/game-bot-go/internal/turtlesoup/config"
	"log/slog"
)

// Injectors from wire.go:

//go:generate go run github.com/google/wire/cmd/wire@v0.7.0
func Initialize(ctx context.Context, cfg *config.Config, logger *slog.Logger) (*bootstrap.ServerApp, func(), error) {
	client, err := newTurtleSoupRestClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	provider, err := newTurtleSoupMessageProvider(cfg)
	if err != nil {
		return nil, nil, err
	}
	mqValkeyClient, cleanup, err := newTurtleSoupMQValkey(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	replyPublisher := newTurtleSoupReplyPublisher(cfg, mqValkeyClient, logger)
	injectionGuard := newTurtleSoupInjectionGuard(cfg, client, logger)
	dataValkeyClient, cleanup2, err := newTurtleSoupDataRedis(ctx, cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appTurtleSoupStores := newTurtleSoupStores(dataValkeyClient, logger)
	appTurtleSoupServices := newTurtleSoupServices(cfg, client, provider, replyPublisher, injectionGuard, appTurtleSoupStores, logger)
	gameService := newTurtleSoupGameService(appTurtleSoupServices)
	serveMux := newTurtleSoupHTTPMux(cfg, client, gameService, logger)
	server := newTurtleSoupHTTPServer(cfg, serveMux)
	streamConsumer := newTurtleSoupStreamConsumer(cfg, mqValkeyClient, logger)
	appTurtleSoupMQPipeline := newTurtleSoupMQPipeline(client, provider, appTurtleSoupStores, appTurtleSoupServices, streamConsumer, logger)
	serverApp := newTurtleSoupServerApp(logger, server, appTurtleSoupMQPipeline)
	return serverApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
