// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: llm/v1/llm_service.proto

package llmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelConfigResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ModelDefault          string                 `protobuf:"bytes,1,opt,name=model_default,json=modelDefault,proto3" json:"model_default,omitempty"`
	ModelHints            *string                `protobuf:"bytes,2,opt,name=model_hints,json=modelHints,proto3,oneof" json:"model_hints,omitempty"`
	ModelAnswer           *string                `protobuf:"bytes,3,opt,name=model_answer,json=modelAnswer,proto3,oneof" json:"model_answer,omitempty"`
	ModelVerify           *string                `protobuf:"bytes,4,opt,name=model_verify,json=modelVerify,proto3,oneof" json:"model_verify,omitempty"`
	Temperature           float64                `protobuf:"fixed64,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	ConfiguredTemperature *float64               `protobuf:"fixed64,6,opt,name=configured_temperature,json=configuredTemperature,proto3,oneof" json:"configured_temperature,omitempty"`
	TimeoutSeconds        int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxRetries            int32                  `protobuf:"varint,8,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Http2Enabled          bool                   `protobuf:"varint,9,opt,name=http2_enabled,json=http2Enabled,proto3" json:"http2_enabled,omitempty"`
	TransportMode         *string                `protobuf:"bytes,10,opt,name=transport_mode,json=transportMode,proto3,oneof" json:"transport_mode,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ModelConfigResponse) Reset() {
	*x = ModelConfigResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConfigResponse) ProtoMessage() {}

func (x *ModelConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelConfigResponse.ProtoReflect.Descriptor instead.
func (*ModelConfigResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{0}
}

func (x *ModelConfigResponse) GetModelDefault() string {
	if x != nil {
		return x.ModelDefault
	}
	return ""
}

func (x *ModelConfigResponse) GetModelHints() string {
	if x != nil && x.ModelHints != nil {
		return *x.ModelHints
	}
	return ""
}

func (x *ModelConfigResponse) GetModelAnswer() string {
	if x != nil && x.ModelAnswer != nil {
		return *x.ModelAnswer
	}
	return ""
}

func (x *ModelConfigResponse) GetModelVerify() string {
	if x != nil && x.ModelVerify != nil {
		return *x.ModelVerify
	}
	return ""
}

func (x *ModelConfigResponse) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ModelConfigResponse) GetConfiguredTemperature() float64 {
	if x != nil && x.ConfiguredTemperature != nil {
		return *x.ConfiguredTemperature
	}
	return 0
}

func (x *ModelConfigResponse) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ModelConfigResponse) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *ModelConfigResponse) GetHttp2Enabled() bool {
	if x != nil {
		return x.Http2Enabled
	}
	return false
}

func (x *ModelConfigResponse) GetTransportMode() string {
	if x != nil && x.TransportMode != nil {
		return *x.TransportMode
	}
	return ""
}

type GuardIsMaliciousRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputText     string                 `protobuf:"bytes,1,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardIsMaliciousRequest) Reset() {
	*x = GuardIsMaliciousRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardIsMaliciousRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardIsMaliciousRequest) ProtoMessage() {}

func (x *GuardIsMaliciousRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardIsMaliciousRequest.ProtoReflect.Descriptor instead.
func (*GuardIsMaliciousRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{1}
}

func (x *GuardIsMaliciousRequest) GetInputText() string {
	if x != nil {
		return x.InputText
	}
	return ""
}

type GuardIsMaliciousResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Malicious     bool                   `protobuf:"varint,1,opt,name=malicious,proto3" json:"malicious,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardIsMaliciousResponse) Reset() {
	*x = GuardIsMaliciousResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardIsMaliciousResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardIsMaliciousResponse) ProtoMessage() {}

func (x *GuardIsMaliciousResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardIsMaliciousResponse.ProtoReflect.Descriptor instead.
func (*GuardIsMaliciousResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{2}
}

func (x *GuardIsMaliciousResponse) GetMalicious() bool {
	if x != nil {
		return x.Malicious
	}
	return false
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{3}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EndSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TwentyQSelectTopicRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Category           string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	BannedTopics       []string               `protobuf:"bytes,2,rep,name=banned_topics,json=bannedTopics,proto3" json:"banned_topics,omitempty"`
	ExcludedCategories []string               `protobuf:"bytes,3,rep,name=excluded_categories,json=excludedCategories,proto3" json:"excluded_categories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TwentyQSelectTopicRequest) Reset() {
	*x = TwentyQSelectTopicRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQSelectTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQSelectTopicRequest) ProtoMessage() {}

func (x *TwentyQSelectTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQSelectTopicRequest.ProtoReflect.Descriptor instead.
func (*TwentyQSelectTopicRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{5}
}

func (x *TwentyQSelectTopicRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TwentyQSelectTopicRequest) GetBannedTopics() []string {
	if x != nil {
		return x.BannedTopics
	}
	return nil
}

func (x *TwentyQSelectTopicRequest) GetExcludedCategories() []string {
	if x != nil {
		return x.ExcludedCategories
	}
	return nil
}

type TwentyQSelectTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQSelectTopicResponse) Reset() {
	*x = TwentyQSelectTopicResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQSelectTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQSelectTopicResponse) ProtoMessage() {}

func (x *TwentyQSelectTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQSelectTopicResponse.ProtoReflect.Descriptor instead.
func (*TwentyQSelectTopicResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{6}
}

func (x *TwentyQSelectTopicResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TwentyQSelectTopicResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TwentyQSelectTopicResponse) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type TwentyQGetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQGetCategoriesResponse) Reset() {
	*x = TwentyQGetCategoriesResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQGetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQGetCategoriesResponse) ProtoMessage() {}

func (x *TwentyQGetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQGetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*TwentyQGetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{7}
}

func (x *TwentyQGetCategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type TwentyQGenerateHintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQGenerateHintsRequest) Reset() {
	*x = TwentyQGenerateHintsRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQGenerateHintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQGenerateHintsRequest) ProtoMessage() {}

func (x *TwentyQGenerateHintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQGenerateHintsRequest.ProtoReflect.Descriptor instead.
func (*TwentyQGenerateHintsRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{8}
}

func (x *TwentyQGenerateHintsRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TwentyQGenerateHintsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TwentyQGenerateHintsRequest) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type TwentyQGenerateHintsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hints            []string               `protobuf:"bytes,1,rep,name=hints,proto3" json:"hints,omitempty"`
	ThoughtSignature *string                `protobuf:"bytes,2,opt,name=thought_signature,json=thoughtSignature,proto3,oneof" json:"thought_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TwentyQGenerateHintsResponse) Reset() {
	*x = TwentyQGenerateHintsResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQGenerateHintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQGenerateHintsResponse) ProtoMessage() {}

func (x *TwentyQGenerateHintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQGenerateHintsResponse.ProtoReflect.Descriptor instead.
func (*TwentyQGenerateHintsResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{9}
}

func (x *TwentyQGenerateHintsResponse) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *TwentyQGenerateHintsResponse) GetThoughtSignature() string {
	if x != nil && x.ThoughtSignature != nil {
		return *x.ThoughtSignature
	}
	return ""
}

type TwentyQAnswerQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	ChatId        *string                `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3,oneof" json:"chat_id,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Question      string                 `protobuf:"bytes,6,opt,name=question,proto3" json:"question,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQAnswerQuestionRequest) Reset() {
	*x = TwentyQAnswerQuestionRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQAnswerQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQAnswerQuestionRequest) ProtoMessage() {}

func (x *TwentyQAnswerQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQAnswerQuestionRequest.ProtoReflect.Descriptor instead.
func (*TwentyQAnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{10}
}

func (x *TwentyQAnswerQuestionRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *TwentyQAnswerQuestionRequest) GetChatId() string {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return ""
}

func (x *TwentyQAnswerQuestionRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *TwentyQAnswerQuestionRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TwentyQAnswerQuestionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TwentyQAnswerQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *TwentyQAnswerQuestionRequest) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type TwentyQAnswerQuestionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Scale            *string                `protobuf:"bytes,1,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	RawText          string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	ThoughtSignature *string                `protobuf:"bytes,3,opt,name=thought_signature,json=thoughtSignature,proto3,oneof" json:"thought_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TwentyQAnswerQuestionResponse) Reset() {
	*x = TwentyQAnswerQuestionResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQAnswerQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQAnswerQuestionResponse) ProtoMessage() {}

func (x *TwentyQAnswerQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQAnswerQuestionResponse.ProtoReflect.Descriptor instead.
func (*TwentyQAnswerQuestionResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{11}
}

func (x *TwentyQAnswerQuestionResponse) GetScale() string {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return ""
}

func (x *TwentyQAnswerQuestionResponse) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *TwentyQAnswerQuestionResponse) GetThoughtSignature() string {
	if x != nil && x.ThoughtSignature != nil {
		return *x.ThoughtSignature
	}
	return ""
}

type TwentyQVerifyGuessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Guess         string                 `protobuf:"bytes,2,opt,name=guess,proto3" json:"guess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQVerifyGuessRequest) Reset() {
	*x = TwentyQVerifyGuessRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQVerifyGuessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQVerifyGuessRequest) ProtoMessage() {}

func (x *TwentyQVerifyGuessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQVerifyGuessRequest.ProtoReflect.Descriptor instead.
func (*TwentyQVerifyGuessRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{12}
}

func (x *TwentyQVerifyGuessRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TwentyQVerifyGuessRequest) GetGuess() string {
	if x != nil {
		return x.Guess
	}
	return ""
}

type TwentyQVerifyGuessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *string                `protobuf:"bytes,1,opt,name=result,proto3,oneof" json:"result,omitempty"`
	RawText       string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQVerifyGuessResponse) Reset() {
	*x = TwentyQVerifyGuessResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQVerifyGuessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQVerifyGuessResponse) ProtoMessage() {}

func (x *TwentyQVerifyGuessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQVerifyGuessResponse.ProtoReflect.Descriptor instead.
func (*TwentyQVerifyGuessResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{13}
}

func (x *TwentyQVerifyGuessResponse) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *TwentyQVerifyGuessResponse) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

type TwentyQNormalizeQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQNormalizeQuestionRequest) Reset() {
	*x = TwentyQNormalizeQuestionRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQNormalizeQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQNormalizeQuestionRequest) ProtoMessage() {}

func (x *TwentyQNormalizeQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQNormalizeQuestionRequest.ProtoReflect.Descriptor instead.
func (*TwentyQNormalizeQuestionRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{14}
}

func (x *TwentyQNormalizeQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type TwentyQNormalizeQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Normalized    string                 `protobuf:"bytes,1,opt,name=normalized,proto3" json:"normalized,omitempty"`
	Original      string                 `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQNormalizeQuestionResponse) Reset() {
	*x = TwentyQNormalizeQuestionResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQNormalizeQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQNormalizeQuestionResponse) ProtoMessage() {}

func (x *TwentyQNormalizeQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQNormalizeQuestionResponse.ProtoReflect.Descriptor instead.
func (*TwentyQNormalizeQuestionResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{15}
}

func (x *TwentyQNormalizeQuestionResponse) GetNormalized() string {
	if x != nil {
		return x.Normalized
	}
	return ""
}

func (x *TwentyQNormalizeQuestionResponse) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type TwentyQCheckSynonymRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Guess         string                 `protobuf:"bytes,2,opt,name=guess,proto3" json:"guess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQCheckSynonymRequest) Reset() {
	*x = TwentyQCheckSynonymRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQCheckSynonymRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQCheckSynonymRequest) ProtoMessage() {}

func (x *TwentyQCheckSynonymRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQCheckSynonymRequest.ProtoReflect.Descriptor instead.
func (*TwentyQCheckSynonymRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{16}
}

func (x *TwentyQCheckSynonymRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TwentyQCheckSynonymRequest) GetGuess() string {
	if x != nil {
		return x.Guess
	}
	return ""
}

type TwentyQCheckSynonymResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *string                `protobuf:"bytes,1,opt,name=result,proto3,oneof" json:"result,omitempty"`
	RawText       string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwentyQCheckSynonymResponse) Reset() {
	*x = TwentyQCheckSynonymResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwentyQCheckSynonymResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwentyQCheckSynonymResponse) ProtoMessage() {}

func (x *TwentyQCheckSynonymResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwentyQCheckSynonymResponse.ProtoReflect.Descriptor instead.
func (*TwentyQCheckSynonymResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{17}
}

func (x *TwentyQCheckSynonymResponse) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *TwentyQCheckSynonymResponse) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

type TurtleSoupGeneratePuzzleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *string                `protobuf:"bytes,1,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Difficulty    *int32                 `protobuf:"varint,2,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	Theme         *string                `protobuf:"bytes,3,opt,name=theme,proto3,oneof" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupGeneratePuzzleRequest) Reset() {
	*x = TurtleSoupGeneratePuzzleRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupGeneratePuzzleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupGeneratePuzzleRequest) ProtoMessage() {}

func (x *TurtleSoupGeneratePuzzleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupGeneratePuzzleRequest.ProtoReflect.Descriptor instead.
func (*TurtleSoupGeneratePuzzleRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{18}
}

func (x *TurtleSoupGeneratePuzzleRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *TurtleSoupGeneratePuzzleRequest) GetDifficulty() int32 {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return 0
}

func (x *TurtleSoupGeneratePuzzleRequest) GetTheme() string {
	if x != nil && x.Theme != nil {
		return *x.Theme
	}
	return ""
}

type TurtleSoupGeneratePuzzleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Scenario      string                 `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Solution      string                 `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty    int32                  `protobuf:"varint,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Hints         []string               `protobuf:"bytes,6,rep,name=hints,proto3" json:"hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupGeneratePuzzleResponse) Reset() {
	*x = TurtleSoupGeneratePuzzleResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupGeneratePuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupGeneratePuzzleResponse) ProtoMessage() {}

func (x *TurtleSoupGeneratePuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupGeneratePuzzleResponse.ProtoReflect.Descriptor instead.
func (*TurtleSoupGeneratePuzzleResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{19}
}

func (x *TurtleSoupGeneratePuzzleResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TurtleSoupGeneratePuzzleResponse) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *TurtleSoupGeneratePuzzleResponse) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TurtleSoupGeneratePuzzleResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TurtleSoupGeneratePuzzleResponse) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *TurtleSoupGeneratePuzzleResponse) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

type TurtleSoupGetRandomPuzzleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Difficulty    *int32                 `protobuf:"varint,1,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupGetRandomPuzzleRequest) Reset() {
	*x = TurtleSoupGetRandomPuzzleRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupGetRandomPuzzleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupGetRandomPuzzleRequest) ProtoMessage() {}

func (x *TurtleSoupGetRandomPuzzleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupGetRandomPuzzleRequest.ProtoReflect.Descriptor instead.
func (*TurtleSoupGetRandomPuzzleRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{20}
}

func (x *TurtleSoupGetRandomPuzzleRequest) GetDifficulty() int32 {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return 0
}

type TurtleSoupGetRandomPuzzleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Question      *string                `protobuf:"bytes,3,opt,name=question,proto3,oneof" json:"question,omitempty"`
	Answer        *string                `protobuf:"bytes,4,opt,name=answer,proto3,oneof" json:"answer,omitempty"`
	Difficulty    *int32                 `protobuf:"varint,5,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupGetRandomPuzzleResponse) Reset() {
	*x = TurtleSoupGetRandomPuzzleResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupGetRandomPuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupGetRandomPuzzleResponse) ProtoMessage() {}

func (x *TurtleSoupGetRandomPuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupGetRandomPuzzleResponse.ProtoReflect.Descriptor instead.
func (*TurtleSoupGetRandomPuzzleResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{21}
}

func (x *TurtleSoupGetRandomPuzzleResponse) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TurtleSoupGetRandomPuzzleResponse) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *TurtleSoupGetRandomPuzzleResponse) GetQuestion() string {
	if x != nil && x.Question != nil {
		return *x.Question
	}
	return ""
}

func (x *TurtleSoupGetRandomPuzzleResponse) GetAnswer() string {
	if x != nil && x.Answer != nil {
		return *x.Answer
	}
	return ""
}

func (x *TurtleSoupGetRandomPuzzleResponse) GetDifficulty() int32 {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return 0
}

type TurtleSoupRewriteScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Scenario      string                 `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Solution      string                 `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"`
	Difficulty    int32                  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupRewriteScenarioRequest) Reset() {
	*x = TurtleSoupRewriteScenarioRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupRewriteScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupRewriteScenarioRequest) ProtoMessage() {}

func (x *TurtleSoupRewriteScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupRewriteScenarioRequest.ProtoReflect.Descriptor instead.
func (*TurtleSoupRewriteScenarioRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{22}
}

func (x *TurtleSoupRewriteScenarioRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TurtleSoupRewriteScenarioRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *TurtleSoupRewriteScenarioRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TurtleSoupRewriteScenarioRequest) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

type TurtleSoupRewriteScenarioResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Scenario         string                 `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Solution         string                 `protobuf:"bytes,2,opt,name=solution,proto3" json:"solution,omitempty"`
	OriginalScenario string                 `protobuf:"bytes,3,opt,name=original_scenario,json=originalScenario,proto3" json:"original_scenario,omitempty"`
	OriginalSolution string                 `protobuf:"bytes,4,opt,name=original_solution,json=originalSolution,proto3" json:"original_solution,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TurtleSoupRewriteScenarioResponse) Reset() {
	*x = TurtleSoupRewriteScenarioResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupRewriteScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupRewriteScenarioResponse) ProtoMessage() {}

func (x *TurtleSoupRewriteScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupRewriteScenarioResponse.ProtoReflect.Descriptor instead.
func (*TurtleSoupRewriteScenarioResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{23}
}

func (x *TurtleSoupRewriteScenarioResponse) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *TurtleSoupRewriteScenarioResponse) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TurtleSoupRewriteScenarioResponse) GetOriginalScenario() string {
	if x != nil {
		return x.OriginalScenario
	}
	return ""
}

func (x *TurtleSoupRewriteScenarioResponse) GetOriginalSolution() string {
	if x != nil {
		return x.OriginalSolution
	}
	return ""
}

type TurtleSoupHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupHistoryItem) Reset() {
	*x = TurtleSoupHistoryItem{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupHistoryItem) ProtoMessage() {}

func (x *TurtleSoupHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupHistoryItem.ProtoReflect.Descriptor instead.
func (*TurtleSoupHistoryItem) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{24}
}

func (x *TurtleSoupHistoryItem) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *TurtleSoupHistoryItem) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type TurtleSoupAnswerQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	ChatId        *string                `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3,oneof" json:"chat_id,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Scenario      string                 `protobuf:"bytes,4,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Solution      string                 `protobuf:"bytes,5,opt,name=solution,proto3" json:"solution,omitempty"`
	Question      string                 `protobuf:"bytes,6,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupAnswerQuestionRequest) Reset() {
	*x = TurtleSoupAnswerQuestionRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupAnswerQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupAnswerQuestionRequest) ProtoMessage() {}

func (x *TurtleSoupAnswerQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupAnswerQuestionRequest.ProtoReflect.Descriptor instead.
func (*TurtleSoupAnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{25}
}

func (x *TurtleSoupAnswerQuestionRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *TurtleSoupAnswerQuestionRequest) GetChatId() string {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return ""
}

func (x *TurtleSoupAnswerQuestionRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *TurtleSoupAnswerQuestionRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *TurtleSoupAnswerQuestionRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TurtleSoupAnswerQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type TurtleSoupAnswerQuestionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Answer        string                   `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	RawText       string                   `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	QuestionCount int32                    `protobuf:"varint,3,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	History       []*TurtleSoupHistoryItem `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupAnswerQuestionResponse) Reset() {
	*x = TurtleSoupAnswerQuestionResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupAnswerQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupAnswerQuestionResponse) ProtoMessage() {}

func (x *TurtleSoupAnswerQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupAnswerQuestionResponse.ProtoReflect.Descriptor instead.
func (*TurtleSoupAnswerQuestionResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{26}
}

func (x *TurtleSoupAnswerQuestionResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *TurtleSoupAnswerQuestionResponse) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *TurtleSoupAnswerQuestionResponse) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *TurtleSoupAnswerQuestionResponse) GetHistory() []*TurtleSoupHistoryItem {
	if x != nil {
		return x.History
	}
	return nil
}

type TurtleSoupValidateSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	ChatId        *string                `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3,oneof" json:"chat_id,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Solution      string                 `protobuf:"bytes,4,opt,name=solution,proto3" json:"solution,omitempty"`
	PlayerAnswer  string                 `protobuf:"bytes,5,opt,name=player_answer,json=playerAnswer,proto3" json:"player_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupValidateSolutionRequest) Reset() {
	*x = TurtleSoupValidateSolutionRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupValidateSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupValidateSolutionRequest) ProtoMessage() {}

func (x *TurtleSoupValidateSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupValidateSolutionRequest.ProtoReflect.Descriptor instead.
func (*TurtleSoupValidateSolutionRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{27}
}

func (x *TurtleSoupValidateSolutionRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *TurtleSoupValidateSolutionRequest) GetChatId() string {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return ""
}

func (x *TurtleSoupValidateSolutionRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *TurtleSoupValidateSolutionRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TurtleSoupValidateSolutionRequest) GetPlayerAnswer() string {
	if x != nil {
		return x.PlayerAnswer
	}
	return ""
}

type TurtleSoupValidateSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	RawText       string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupValidateSolutionResponse) Reset() {
	*x = TurtleSoupValidateSolutionResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupValidateSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupValidateSolutionResponse) ProtoMessage() {}

func (x *TurtleSoupValidateSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupValidateSolutionResponse.ProtoReflect.Descriptor instead.
func (*TurtleSoupValidateSolutionResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{28}
}

func (x *TurtleSoupValidateSolutionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TurtleSoupValidateSolutionResponse) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

type TurtleSoupGenerateHintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	ChatId        *string                `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3,oneof" json:"chat_id,omitempty"`
	Namespace     *string                `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Scenario      string                 `protobuf:"bytes,4,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Solution      string                 `protobuf:"bytes,5,opt,name=solution,proto3" json:"solution,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupGenerateHintRequest) Reset() {
	*x = TurtleSoupGenerateHintRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupGenerateHintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupGenerateHintRequest) ProtoMessage() {}

func (x *TurtleSoupGenerateHintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupGenerateHintRequest.ProtoReflect.Descriptor instead.
func (*TurtleSoupGenerateHintRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{29}
}

func (x *TurtleSoupGenerateHintRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *TurtleSoupGenerateHintRequest) GetChatId() string {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return ""
}

func (x *TurtleSoupGenerateHintRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *TurtleSoupGenerateHintRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *TurtleSoupGenerateHintRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TurtleSoupGenerateHintRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type TurtleSoupGenerateHintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hint          string                 `protobuf:"bytes,1,opt,name=hint,proto3" json:"hint,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurtleSoupGenerateHintResponse) Reset() {
	*x = TurtleSoupGenerateHintResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurtleSoupGenerateHintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurtleSoupGenerateHintResponse) ProtoMessage() {}

func (x *TurtleSoupGenerateHintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurtleSoupGenerateHintResponse.ProtoReflect.Descriptor instead.
func (*TurtleSoupGenerateHintResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{30}
}

func (x *TurtleSoupGenerateHintResponse) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *TurtleSoupGenerateHintResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type DailyUsageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UsageDate       string                 `protobuf:"bytes,1,opt,name=usage_date,json=usageDate,proto3" json:"usage_date,omitempty"`
	InputTokens     int64                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens    int64                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens     int64                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ReasoningTokens int64                  `protobuf:"varint,5,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	RequestCount    int64                  `protobuf:"varint,6,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	Model           string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyUsageResponse) Reset() {
	*x = DailyUsageResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyUsageResponse) ProtoMessage() {}

func (x *DailyUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyUsageResponse.ProtoReflect.Descriptor instead.
func (*DailyUsageResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{31}
}

func (x *DailyUsageResponse) GetUsageDate() string {
	if x != nil {
		return x.UsageDate
	}
	return ""
}

func (x *DailyUsageResponse) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *DailyUsageResponse) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *DailyUsageResponse) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *DailyUsageResponse) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *DailyUsageResponse) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *DailyUsageResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type UsageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InputTokens     int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens    int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens     int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ReasoningTokens int64                  `protobuf:"varint,4,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	Model           string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UsageResponse) Reset() {
	*x = UsageResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageResponse) ProtoMessage() {}

func (x *UsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageResponse.ProtoReflect.Descriptor instead.
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{32}
}

func (x *UsageResponse) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageResponse) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageResponse) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *UsageResponse) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *UsageResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GetRecentUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentUsageRequest) Reset() {
	*x = GetRecentUsageRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentUsageRequest) ProtoMessage() {}

func (x *GetRecentUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentUsageRequest.ProtoReflect.Descriptor instead.
func (*GetRecentUsageRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{33}
}

func (x *GetRecentUsageRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type UsageListResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Usages            []*DailyUsageResponse  `protobuf:"bytes,1,rep,name=usages,proto3" json:"usages,omitempty"`
	TotalInputTokens  int64                  `protobuf:"varint,2,opt,name=total_input_tokens,json=totalInputTokens,proto3" json:"total_input_tokens,omitempty"`
	TotalOutputTokens int64                  `protobuf:"varint,3,opt,name=total_output_tokens,json=totalOutputTokens,proto3" json:"total_output_tokens,omitempty"`
	TotalTokens       int64                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalRequestCount int64                  `protobuf:"varint,5,opt,name=total_request_count,json=totalRequestCount,proto3" json:"total_request_count,omitempty"`
	Model             string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UsageListResponse) Reset() {
	*x = UsageListResponse{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageListResponse) ProtoMessage() {}

func (x *UsageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageListResponse.ProtoReflect.Descriptor instead.
func (*UsageListResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{34}
}

func (x *UsageListResponse) GetUsages() []*DailyUsageResponse {
	if x != nil {
		return x.Usages
	}
	return nil
}

func (x *UsageListResponse) GetTotalInputTokens() int64 {
	if x != nil {
		return x.TotalInputTokens
	}
	return 0
}

func (x *UsageListResponse) GetTotalOutputTokens() int64 {
	if x != nil {
		return x.TotalOutputTokens
	}
	return 0
}

func (x *UsageListResponse) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *UsageListResponse) GetTotalRequestCount() int64 {
	if x != nil {
		return x.TotalRequestCount
	}
	return 0
}

func (x *UsageListResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GetTotalUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalUsageRequest) Reset() {
	*x = GetTotalUsageRequest{}
	mi := &file_llm_v1_llm_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalUsageRequest) ProtoMessage() {}

func (x *GetTotalUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalUsageRequest.ProtoReflect.Descriptor instead.
func (*GetTotalUsageRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_service_proto_rawDescGZIP(), []int{35}
}

func (x *GetTotalUsageRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

var File_llm_v1_llm_service_proto protoreflect.FileDescriptor

const file_llm_v1_llm_service_proto_rawDesc = "" +
	"\n" +
	"\x18llm/v1/llm_service.proto\x12\x06llm.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x89\x04\n" +
	"\x13ModelConfigResponse\x12#\n" +
	"\rmodel_default\x18\x01 \x01(\tR\fmodelDefault\x12$\n" +
	"\vmodel_hints\x18\x02 \x01(\tH\x00R\n" +
	"modelHints\x88\x01\x01\x12&\n" +
	"\fmodel_answer\x18\x03 \x01(\tH\x01R\vmodelAnswer\x88\x01\x01\x12&\n" +
	"\fmodel_verify\x18\x04 \x01(\tH\x02R\vmodelVerify\x88\x01\x01\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x01R\vtemperature\x12:\n" +
	"\x16configured_temperature\x18\x06 \x01(\x01H\x03R\x15configuredTemperature\x88\x01\x01\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vmax_retries\x18\b \x01(\x05R\n" +
	"maxRetries\x12#\n" +
	"\rhttp2_enabled\x18\t \x01(\bR\fhttp2Enabled\x12*\n" +
	"\x0etransport_mode\x18\n" +
	" \x01(\tH\x04R\rtransportMode\x88\x01\x01B\x0e\n" +
	"\f_model_hintsB\x0f\n" +
	"\r_model_answerB\x0f\n" +
	"\r_model_verifyB\x19\n" +
	"\x17_configured_temperatureB\x11\n" +
	"\x0f_transport_mode\"8\n" +
	"\x17GuardIsMaliciousRequest\x12\x1d\n" +
	"\n" +
	"input_text\x18\x01 \x01(\tR\tinputText\"8\n" +
	"\x18GuardIsMaliciousResponse\x12\x1c\n" +
	"\tmalicious\x18\x01 \x01(\bR\tmalicious\"2\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\">\n" +
	"\x12EndSessionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x8d\x01\n" +
	"\x19TwentyQSelectTopicRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12#\n" +
	"\rbanned_topics\x18\x02 \x03(\tR\fbannedTopics\x12/\n" +
	"\x13excluded_categories\x18\x03 \x03(\tR\x12excludedCategories\"\x7f\n" +
	"\x1aTwentyQSelectTopicResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\">\n" +
	"\x1cTwentyQGetCategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"\x84\x01\n" +
	"\x1bTwentyQGenerateHintsRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\"|\n" +
	"\x1cTwentyQGenerateHintsResponse\x12\x14\n" +
	"\x05hints\x18\x01 \x03(\tR\x05hints\x120\n" +
	"\x11thought_signature\x18\x02 \x01(\tH\x00R\x10thoughtSignature\x88\x01\x01B\x14\n" +
	"\x12_thought_signature\"\xaf\x02\n" +
	"\x1cTwentyQAnswerQuestionRequest\x12\"\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\achat_id\x18\x02 \x01(\tH\x01R\x06chatId\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x02R\tnamespace\x88\x01\x01\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1a\n" +
	"\bquestion\x18\x06 \x01(\tR\bquestion\x121\n" +
	"\adetails\x18\a \x01(\v2\x17.google.protobuf.StructR\adetailsB\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_chat_idB\f\n" +
	"\n" +
	"_namespace\"\xa7\x01\n" +
	"\x1dTwentyQAnswerQuestionResponse\x12\x19\n" +
	"\x05scale\x18\x01 \x01(\tH\x00R\x05scale\x88\x01\x01\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\x120\n" +
	"\x11thought_signature\x18\x03 \x01(\tH\x01R\x10thoughtSignature\x88\x01\x01B\b\n" +
	"\x06_scaleB\x14\n" +
	"\x12_thought_signature\"I\n" +
	"\x19TwentyQVerifyGuessRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05guess\x18\x02 \x01(\tR\x05guess\"_\n" +
	"\x1aTwentyQVerifyGuessResponse\x12\x1b\n" +
	"\x06result\x18\x01 \x01(\tH\x00R\x06result\x88\x01\x01\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawTextB\t\n" +
	"\a_result\"=\n" +
	"\x1fTwentyQNormalizeQuestionRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"^\n" +
	" TwentyQNormalizeQuestionResponse\x12\x1e\n" +
	"\n" +
	"normalized\x18\x01 \x01(\tR\n" +
	"normalized\x12\x1a\n" +
	"\boriginal\x18\x02 \x01(\tR\boriginal\"J\n" +
	"\x1aTwentyQCheckSynonymRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05guess\x18\x02 \x01(\tR\x05guess\"`\n" +
	"\x1bTwentyQCheckSynonymResponse\x12\x1b\n" +
	"\x06result\x18\x01 \x01(\tH\x00R\x06result\x88\x01\x01\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawTextB\t\n" +
	"\a_result\"\xa8\x01\n" +
	"\x1fTurtleSoupGeneratePuzzleRequest\x12\x1f\n" +
	"\bcategory\x18\x01 \x01(\tH\x00R\bcategory\x88\x01\x01\x12#\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\x05H\x01R\n" +
	"difficulty\x88\x01\x01\x12\x19\n" +
	"\x05theme\x18\x03 \x01(\tH\x02R\x05theme\x88\x01\x01B\v\n" +
	"\t_categoryB\r\n" +
	"\v_difficultyB\b\n" +
	"\x06_theme\"\xc2\x01\n" +
	" TurtleSoupGeneratePuzzleResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bscenario\x18\x02 \x01(\tR\bscenario\x12\x1a\n" +
	"\bsolution\x18\x03 \x01(\tR\bsolution\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x05R\n" +
	"difficulty\x12\x14\n" +
	"\x05hints\x18\x06 \x03(\tR\x05hints\"V\n" +
	" TurtleSoupGetRandomPuzzleRequest\x12#\n" +
	"\n" +
	"difficulty\x18\x01 \x01(\x05H\x00R\n" +
	"difficulty\x88\x01\x01B\r\n" +
	"\v_difficulty\"\xee\x01\n" +
	"!TurtleSoupGetRandomPuzzleResponse\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x01R\x05title\x88\x01\x01\x12\x1f\n" +
	"\bquestion\x18\x03 \x01(\tH\x02R\bquestion\x88\x01\x01\x12\x1b\n" +
	"\x06answer\x18\x04 \x01(\tH\x03R\x06answer\x88\x01\x01\x12#\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x05H\x04R\n" +
	"difficulty\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_titleB\v\n" +
	"\t_questionB\t\n" +
	"\a_answerB\r\n" +
	"\v_difficulty\"\x90\x01\n" +
	" TurtleSoupRewriteScenarioRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bscenario\x18\x02 \x01(\tR\bscenario\x12\x1a\n" +
	"\bsolution\x18\x03 \x01(\tR\bsolution\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x05R\n" +
	"difficulty\"\xb5\x01\n" +
	"!TurtleSoupRewriteScenarioResponse\x12\x1a\n" +
	"\bscenario\x18\x01 \x01(\tR\bscenario\x12\x1a\n" +
	"\bsolution\x18\x02 \x01(\tR\bsolution\x12+\n" +
	"\x11original_scenario\x18\x03 \x01(\tR\x10originalScenario\x12+\n" +
	"\x11original_solution\x18\x04 \x01(\tR\x10originalSolution\"K\n" +
	"\x15TurtleSoupHistoryItem\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"\x83\x02\n" +
	"\x1fTurtleSoupAnswerQuestionRequest\x12\"\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\achat_id\x18\x02 \x01(\tH\x01R\x06chatId\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x02R\tnamespace\x88\x01\x01\x12\x1a\n" +
	"\bscenario\x18\x04 \x01(\tR\bscenario\x12\x1a\n" +
	"\bsolution\x18\x05 \x01(\tR\bsolution\x12\x1a\n" +
	"\bquestion\x18\x06 \x01(\tR\bquestionB\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_chat_idB\f\n" +
	"\n" +
	"_namespace\"\xb5\x01\n" +
	" TurtleSoupAnswerQuestionResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\x12%\n" +
	"\x0equestion_count\x18\x03 \x01(\x05R\rquestionCount\x127\n" +
	"\ahistory\x18\x04 \x03(\v2\x1d.llm.v1.TurtleSoupHistoryItemR\ahistory\"\xf2\x01\n" +
	"!TurtleSoupValidateSolutionRequest\x12\"\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\achat_id\x18\x02 \x01(\tH\x01R\x06chatId\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x02R\tnamespace\x88\x01\x01\x12\x1a\n" +
	"\bsolution\x18\x04 \x01(\tR\bsolution\x12#\n" +
	"\rplayer_answer\x18\x05 \x01(\tR\fplayerAnswerB\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_chat_idB\f\n" +
	"\n" +
	"_namespace\"W\n" +
	"\"TurtleSoupValidateSolutionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\"\xfb\x01\n" +
	"\x1dTurtleSoupGenerateHintRequest\x12\"\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\achat_id\x18\x02 \x01(\tH\x01R\x06chatId\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x02R\tnamespace\x88\x01\x01\x12\x1a\n" +
	"\bscenario\x18\x04 \x01(\tR\bscenario\x12\x1a\n" +
	"\bsolution\x18\x05 \x01(\tR\bsolution\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05levelB\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_chat_idB\f\n" +
	"\n" +
	"_namespace\"J\n" +
	"\x1eTurtleSoupGenerateHintResponse\x12\x12\n" +
	"\x04hint\x18\x01 \x01(\tR\x04hint\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\x84\x02\n" +
	"\x12DailyUsageResponse\x12\x1d\n" +
	"\n" +
	"usage_date\x18\x01 \x01(\tR\tusageDate\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x03R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x03R\vtotalTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x05 \x01(\x03R\x0freasoningTokens\x12#\n" +
	"\rrequest_count\x18\x06 \x01(\x03R\frequestCount\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\"\xbb\x01\n" +
	"\rUsageResponse\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x04 \x01(\x03R\x0freasoningTokens\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"+\n" +
	"\x15GetRecentUsageRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"\x8e\x02\n" +
	"\x11UsageListResponse\x122\n" +
	"\x06usages\x18\x01 \x03(\v2\x1a.llm.v1.DailyUsageResponseR\x06usages\x12,\n" +
	"\x12total_input_tokens\x18\x02 \x01(\x03R\x10totalInputTokens\x12.\n" +
	"\x13total_output_tokens\x18\x03 \x01(\x03R\x11totalOutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x03R\vtotalTokens\x12.\n" +
	"\x13total_request_count\x18\x05 \x01(\x03R\x11totalRequestCount\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\"*\n" +
	"\x14GetTotalUsageRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days2\x8e\x0e\n" +
	"\n" +
	"LLMService\x12E\n" +
	"\x0eGetModelConfig\x12\x16.google.protobuf.Empty\x1a\x1b.llm.v1.ModelConfigResponse\x12U\n" +
	"\x10GuardIsMalicious\x12\x1f.llm.v1.GuardIsMaliciousRequest\x1a .llm.v1.GuardIsMaliciousResponse\x12C\n" +
	"\n" +
	"EndSession\x12\x19.llm.v1.EndSessionRequest\x1a\x1a.llm.v1.EndSessionResponse\x12[\n" +
	"\x12TwentyQSelectTopic\x12!.llm.v1.TwentyQSelectTopicRequest\x1a\".llm.v1.TwentyQSelectTopicResponse\x12T\n" +
	"\x14TwentyQGetCategories\x12\x16.google.protobuf.Empty\x1a$.llm.v1.TwentyQGetCategoriesResponse\x12a\n" +
	"\x14TwentyQGenerateHints\x12#.llm.v1.TwentyQGenerateHintsRequest\x1a$.llm.v1.TwentyQGenerateHintsResponse\x12d\n" +
	"\x15TwentyQAnswerQuestion\x12$.llm.v1.TwentyQAnswerQuestionRequest\x1a%.llm.v1.TwentyQAnswerQuestionResponse\x12[\n" +
	"\x12TwentyQVerifyGuess\x12!.llm.v1.TwentyQVerifyGuessRequest\x1a\".llm.v1.TwentyQVerifyGuessResponse\x12m\n" +
	"\x18TwentyQNormalizeQuestion\x12'.llm.v1.TwentyQNormalizeQuestionRequest\x1a(.llm.v1.TwentyQNormalizeQuestionResponse\x12^\n" +
	"\x13TwentyQCheckSynonym\x12\".llm.v1.TwentyQCheckSynonymRequest\x1a#.llm.v1.TwentyQCheckSynonymResponse\x12m\n" +
	"\x18TurtleSoupGeneratePuzzle\x12'.llm.v1.TurtleSoupGeneratePuzzleRequest\x1a(.llm.v1.TurtleSoupGeneratePuzzleResponse\x12p\n" +
	"\x19TurtleSoupGetRandomPuzzle\x12(.llm.v1.TurtleSoupGetRandomPuzzleRequest\x1a).llm.v1.TurtleSoupGetRandomPuzzleResponse\x12p\n" +
	"\x19TurtleSoupRewriteScenario\x12(.llm.v1.TurtleSoupRewriteScenarioRequest\x1a).llm.v1.TurtleSoupRewriteScenarioResponse\x12m\n" +
	"\x18TurtleSoupAnswerQuestion\x12'.llm.v1.TurtleSoupAnswerQuestionRequest\x1a(.llm.v1.TurtleSoupAnswerQuestionResponse\x12s\n" +
	"\x1aTurtleSoupValidateSolution\x12).llm.v1.TurtleSoupValidateSolutionRequest\x1a*.llm.v1.TurtleSoupValidateSolutionResponse\x12g\n" +
	"\x16TurtleSoupGenerateHint\x12%.llm.v1.TurtleSoupGenerateHintRequest\x1a&.llm.v1.TurtleSoupGenerateHintResponse\x12C\n" +
	"\rGetDailyUsage\x12\x16.google.protobuf.Empty\x1a\x1a.llm.v1.DailyUsageResponse\x12J\n" +
	"\x0eGetRecentUsage\x12\x1d.llm.v1.GetRecentUsageRequest\x1a\x19.llm.v1.UsageListResponse\x12D\n" +
	"\rGetTotalUsage\x12\x1c.llm.v1.GetTotalUsageRequest\x1a\x15.llm.v1.UsageResponseBEZCgithub.com/park285/llm-kakao-bots/llm-kakao-bots-proto/llm/v1;llmv1b\x06proto3"

var (
	file_llm_v1_llm_service_proto_rawDescOnce sync.Once
	file_llm_v1_llm_service_proto_rawDescData []byte
)

func file_llm_v1_llm_service_proto_rawDescGZIP() []byte {
	file_llm_v1_llm_service_proto_rawDescOnce.Do(func() {
		file_llm_v1_llm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_v1_llm_service_proto_rawDesc), len(file_llm_v1_llm_service_proto_rawDesc)))
	})
	return file_llm_v1_llm_service_proto_rawDescData
}

var file_llm_v1_llm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_llm_v1_llm_service_proto_goTypes = []any{
	(*ModelConfigResponse)(nil),                // 0: llm.v1.ModelConfigResponse
	(*GuardIsMaliciousRequest)(nil),            // 1: llm.v1.GuardIsMaliciousRequest
	(*GuardIsMaliciousResponse)(nil),           // 2: llm.v1.GuardIsMaliciousResponse
	(*EndSessionRequest)(nil),                  // 3: llm.v1.EndSessionRequest
	(*EndSessionResponse)(nil),                 // 4: llm.v1.EndSessionResponse
	(*TwentyQSelectTopicRequest)(nil),          // 5: llm.v1.TwentyQSelectTopicRequest
	(*TwentyQSelectTopicResponse)(nil),         // 6: llm.v1.TwentyQSelectTopicResponse
	(*TwentyQGetCategoriesResponse)(nil),       // 7: llm.v1.TwentyQGetCategoriesResponse
	(*TwentyQGenerateHintsRequest)(nil),        // 8: llm.v1.TwentyQGenerateHintsRequest
	(*TwentyQGenerateHintsResponse)(nil),       // 9: llm.v1.TwentyQGenerateHintsResponse
	(*TwentyQAnswerQuestionRequest)(nil),       // 10: llm.v1.TwentyQAnswerQuestionRequest
	(*TwentyQAnswerQuestionResponse)(nil),      // 11: llm.v1.TwentyQAnswerQuestionResponse
	(*TwentyQVerifyGuessRequest)(nil),          // 12: llm.v1.TwentyQVerifyGuessRequest
	(*TwentyQVerifyGuessResponse)(nil),         // 13: llm.v1.TwentyQVerifyGuessResponse
	(*TwentyQNormalizeQuestionRequest)(nil),    // 14: llm.v1.TwentyQNormalizeQuestionRequest
	(*TwentyQNormalizeQuestionResponse)(nil),   // 15: llm.v1.TwentyQNormalizeQuestionResponse
	(*TwentyQCheckSynonymRequest)(nil),         // 16: llm.v1.TwentyQCheckSynonymRequest
	(*TwentyQCheckSynonymResponse)(nil),        // 17: llm.v1.TwentyQCheckSynonymResponse
	(*TurtleSoupGeneratePuzzleRequest)(nil),    // 18: llm.v1.TurtleSoupGeneratePuzzleRequest
	(*TurtleSoupGeneratePuzzleResponse)(nil),   // 19: llm.v1.TurtleSoupGeneratePuzzleResponse
	(*TurtleSoupGetRandomPuzzleRequest)(nil),   // 20: llm.v1.TurtleSoupGetRandomPuzzleRequest
	(*TurtleSoupGetRandomPuzzleResponse)(nil),  // 21: llm.v1.TurtleSoupGetRandomPuzzleResponse
	(*TurtleSoupRewriteScenarioRequest)(nil),   // 22: llm.v1.TurtleSoupRewriteScenarioRequest
	(*TurtleSoupRewriteScenarioResponse)(nil),  // 23: llm.v1.TurtleSoupRewriteScenarioResponse
	(*TurtleSoupHistoryItem)(nil),              // 24: llm.v1.TurtleSoupHistoryItem
	(*TurtleSoupAnswerQuestionRequest)(nil),    // 25: llm.v1.TurtleSoupAnswerQuestionRequest
	(*TurtleSoupAnswerQuestionResponse)(nil),   // 26: llm.v1.TurtleSoupAnswerQuestionResponse
	(*TurtleSoupValidateSolutionRequest)(nil),  // 27: llm.v1.TurtleSoupValidateSolutionRequest
	(*TurtleSoupValidateSolutionResponse)(nil), // 28: llm.v1.TurtleSoupValidateSolutionResponse
	(*TurtleSoupGenerateHintRequest)(nil),      // 29: llm.v1.TurtleSoupGenerateHintRequest
	(*TurtleSoupGenerateHintResponse)(nil),     // 30: llm.v1.TurtleSoupGenerateHintResponse
	(*DailyUsageResponse)(nil),                 // 31: llm.v1.DailyUsageResponse
	(*UsageResponse)(nil),                      // 32: llm.v1.UsageResponse
	(*GetRecentUsageRequest)(nil),              // 33: llm.v1.GetRecentUsageRequest
	(*UsageListResponse)(nil),                  // 34: llm.v1.UsageListResponse
	(*GetTotalUsageRequest)(nil),               // 35: llm.v1.GetTotalUsageRequest
	(*structpb.Struct)(nil),                    // 36: google.protobuf.Struct
	(*emptypb.Empty)(nil),                      // 37: google.protobuf.Empty
}
var file_llm_v1_llm_service_proto_depIdxs = []int32{
	36, // 0: llm.v1.TwentyQSelectTopicResponse.details:type_name -> google.protobuf.Struct
	36, // 1: llm.v1.TwentyQGenerateHintsRequest.details:type_name -> google.protobuf.Struct
	36, // 2: llm.v1.TwentyQAnswerQuestionRequest.details:type_name -> google.protobuf.Struct
	24, // 3: llm.v1.TurtleSoupAnswerQuestionResponse.history:type_name -> llm.v1.TurtleSoupHistoryItem
	31, // 4: llm.v1.UsageListResponse.usages:type_name -> llm.v1.DailyUsageResponse
	37, // 5: llm.v1.LLMService.GetModelConfig:input_type -> google.protobuf.Empty
	1,  // 6: llm.v1.LLMService.GuardIsMalicious:input_type -> llm.v1.GuardIsMaliciousRequest
	3,  // 7: llm.v1.LLMService.EndSession:input_type -> llm.v1.EndSessionRequest
	5,  // 8: llm.v1.LLMService.TwentyQSelectTopic:input_type -> llm.v1.TwentyQSelectTopicRequest
	37, // 9: llm.v1.LLMService.TwentyQGetCategories:input_type -> google.protobuf.Empty
	8,  // 10: llm.v1.LLMService.TwentyQGenerateHints:input_type -> llm.v1.TwentyQGenerateHintsRequest
	10, // 11: llm.v1.LLMService.TwentyQAnswerQuestion:input_type -> llm.v1.TwentyQAnswerQuestionRequest
	12, // 12: llm.v1.LLMService.TwentyQVerifyGuess:input_type -> llm.v1.TwentyQVerifyGuessRequest
	14, // 13: llm.v1.LLMService.TwentyQNormalizeQuestion:input_type -> llm.v1.TwentyQNormalizeQuestionRequest
	16, // 14: llm.v1.LLMService.TwentyQCheckSynonym:input_type -> llm.v1.TwentyQCheckSynonymRequest
	18, // 15: llm.v1.LLMService.TurtleSoupGeneratePuzzle:input_type -> llm.v1.TurtleSoupGeneratePuzzleRequest
	20, // 16: llm.v1.LLMService.TurtleSoupGetRandomPuzzle:input_type -> llm.v1.TurtleSoupGetRandomPuzzleRequest
	22, // 17: llm.v1.LLMService.TurtleSoupRewriteScenario:input_type -> llm.v1.TurtleSoupRewriteScenarioRequest
	25, // 18: llm.v1.LLMService.TurtleSoupAnswerQuestion:input_type -> llm.v1.TurtleSoupAnswerQuestionRequest
	27, // 19: llm.v1.LLMService.TurtleSoupValidateSolution:input_type -> llm.v1.TurtleSoupValidateSolutionRequest
	29, // 20: llm.v1.LLMService.TurtleSoupGenerateHint:input_type -> llm.v1.TurtleSoupGenerateHintRequest
	37, // 21: llm.v1.LLMService.GetDailyUsage:input_type -> google.protobuf.Empty
	33, // 22: llm.v1.LLMService.GetRecentUsage:input_type -> llm.v1.GetRecentUsageRequest
	35, // 23: llm.v1.LLMService.GetTotalUsage:input_type -> llm.v1.GetTotalUsageRequest
	0,  // 24: llm.v1.LLMService.GetModelConfig:output_type -> llm.v1.ModelConfigResponse
	2,  // 25: llm.v1.LLMService.GuardIsMalicious:output_type -> llm.v1.GuardIsMaliciousResponse
	4,  // 26: llm.v1.LLMService.EndSession:output_type -> llm.v1.EndSessionResponse
	6,  // 27: llm.v1.LLMService.TwentyQSelectTopic:output_type -> llm.v1.TwentyQSelectTopicResponse
	7,  // 28: llm.v1.LLMService.TwentyQGetCategories:output_type -> llm.v1.TwentyQGetCategoriesResponse
	9,  // 29: llm.v1.LLMService.TwentyQGenerateHints:output_type -> llm.v1.TwentyQGenerateHintsResponse
	11, // 30: llm.v1.LLMService.TwentyQAnswerQuestion:output_type -> llm.v1.TwentyQAnswerQuestionResponse
	13, // 31: llm.v1.LLMService.TwentyQVerifyGuess:output_type -> llm.v1.TwentyQVerifyGuessResponse
	15, // 32: llm.v1.LLMService.TwentyQNormalizeQuestion:output_type -> llm.v1.TwentyQNormalizeQuestionResponse
	17, // 33: llm.v1.LLMService.TwentyQCheckSynonym:output_type -> llm.v1.TwentyQCheckSynonymResponse
	19, // 34: llm.v1.LLMService.TurtleSoupGeneratePuzzle:output_type -> llm.v1.TurtleSoupGeneratePuzzleResponse
	21, // 35: llm.v1.LLMService.TurtleSoupGetRandomPuzzle:output_type -> llm.v1.TurtleSoupGetRandomPuzzleResponse
	23, // 36: llm.v1.LLMService.TurtleSoupRewriteScenario:output_type -> llm.v1.TurtleSoupRewriteScenarioResponse
	26, // 37: llm.v1.LLMService.TurtleSoupAnswerQuestion:output_type -> llm.v1.TurtleSoupAnswerQuestionResponse
	28, // 38: llm.v1.LLMService.TurtleSoupValidateSolution:output_type -> llm.v1.TurtleSoupValidateSolutionResponse
	30, // 39: llm.v1.LLMService.TurtleSoupGenerateHint:output_type -> llm.v1.TurtleSoupGenerateHintResponse
	31, // 40: llm.v1.LLMService.GetDailyUsage:output_type -> llm.v1.DailyUsageResponse
	34, // 41: llm.v1.LLMService.GetRecentUsage:output_type -> llm.v1.UsageListResponse
	32, // 42: llm.v1.LLMService.GetTotalUsage:output_type -> llm.v1.UsageResponse
	24, // [24:43] is the sub-list for method output_type
	5,  // [5:24] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_llm_v1_llm_service_proto_init() }
func file_llm_v1_llm_service_proto_init() {
	if File_llm_v1_llm_service_proto != nil {
		return
	}
	file_llm_v1_llm_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[17].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[18].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[20].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[21].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[25].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[27].OneofWrappers = []any{}
	file_llm_v1_llm_service_proto_msgTypes[29].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_v1_llm_service_proto_rawDesc), len(file_llm_v1_llm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_v1_llm_service_proto_goTypes,
		DependencyIndexes: file_llm_v1_llm_service_proto_depIdxs,
		MessageInfos:      file_llm_v1_llm_service_proto_msgTypes,
	}.Build()
	File_llm_v1_llm_service_proto = out.File
	file_llm_v1_llm_service_proto_goTypes = nil
	file_llm_v1_llm_service_proto_depIdxs = nil
}
