// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: llm/v1/llm_service.proto

package llmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMService_GetModelConfig_FullMethodName             = "/llm.v1.LLMService/GetModelConfig"
	LLMService_GuardIsMalicious_FullMethodName           = "/llm.v1.LLMService/GuardIsMalicious"
	LLMService_EndSession_FullMethodName                 = "/llm.v1.LLMService/EndSession"
	LLMService_TwentyQSelectTopic_FullMethodName         = "/llm.v1.LLMService/TwentyQSelectTopic"
	LLMService_TwentyQGetCategories_FullMethodName       = "/llm.v1.LLMService/TwentyQGetCategories"
	LLMService_TwentyQGenerateHints_FullMethodName       = "/llm.v1.LLMService/TwentyQGenerateHints"
	LLMService_TwentyQAnswerQuestion_FullMethodName      = "/llm.v1.LLMService/TwentyQAnswerQuestion"
	LLMService_TwentyQVerifyGuess_FullMethodName         = "/llm.v1.LLMService/TwentyQVerifyGuess"
	LLMService_TwentyQNormalizeQuestion_FullMethodName   = "/llm.v1.LLMService/TwentyQNormalizeQuestion"
	LLMService_TwentyQCheckSynonym_FullMethodName        = "/llm.v1.LLMService/TwentyQCheckSynonym"
	LLMService_TurtleSoupGeneratePuzzle_FullMethodName   = "/llm.v1.LLMService/TurtleSoupGeneratePuzzle"
	LLMService_TurtleSoupGetRandomPuzzle_FullMethodName  = "/llm.v1.LLMService/TurtleSoupGetRandomPuzzle"
	LLMService_TurtleSoupRewriteScenario_FullMethodName  = "/llm.v1.LLMService/TurtleSoupRewriteScenario"
	LLMService_TurtleSoupAnswerQuestion_FullMethodName   = "/llm.v1.LLMService/TurtleSoupAnswerQuestion"
	LLMService_TurtleSoupValidateSolution_FullMethodName = "/llm.v1.LLMService/TurtleSoupValidateSolution"
	LLMService_TurtleSoupGenerateHint_FullMethodName     = "/llm.v1.LLMService/TurtleSoupGenerateHint"
	LLMService_GetDailyUsage_FullMethodName              = "/llm.v1.LLMService/GetDailyUsage"
	LLMService_GetRecentUsage_FullMethodName             = "/llm.v1.LLMService/GetRecentUsage"
	LLMService_GetTotalUsage_FullMethodName              = "/llm.v1.LLMService/GetTotalUsage"
)

// LLMServiceClient is the client API for LLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMServiceClient interface {
	GetModelConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ModelConfigResponse, error)
	GuardIsMalicious(ctx context.Context, in *GuardIsMaliciousRequest, opts ...grpc.CallOption) (*GuardIsMaliciousResponse, error)
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	TwentyQSelectTopic(ctx context.Context, in *TwentyQSelectTopicRequest, opts ...grpc.CallOption) (*TwentyQSelectTopicResponse, error)
	TwentyQGetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TwentyQGetCategoriesResponse, error)
	TwentyQGenerateHints(ctx context.Context, in *TwentyQGenerateHintsRequest, opts ...grpc.CallOption) (*TwentyQGenerateHintsResponse, error)
	TwentyQAnswerQuestion(ctx context.Context, in *TwentyQAnswerQuestionRequest, opts ...grpc.CallOption) (*TwentyQAnswerQuestionResponse, error)
	TwentyQVerifyGuess(ctx context.Context, in *TwentyQVerifyGuessRequest, opts ...grpc.CallOption) (*TwentyQVerifyGuessResponse, error)
	TwentyQNormalizeQuestion(ctx context.Context, in *TwentyQNormalizeQuestionRequest, opts ...grpc.CallOption) (*TwentyQNormalizeQuestionResponse, error)
	TwentyQCheckSynonym(ctx context.Context, in *TwentyQCheckSynonymRequest, opts ...grpc.CallOption) (*TwentyQCheckSynonymResponse, error)
	TurtleSoupGeneratePuzzle(ctx context.Context, in *TurtleSoupGeneratePuzzleRequest, opts ...grpc.CallOption) (*TurtleSoupGeneratePuzzleResponse, error)
	TurtleSoupGetRandomPuzzle(ctx context.Context, in *TurtleSoupGetRandomPuzzleRequest, opts ...grpc.CallOption) (*TurtleSoupGetRandomPuzzleResponse, error)
	TurtleSoupRewriteScenario(ctx context.Context, in *TurtleSoupRewriteScenarioRequest, opts ...grpc.CallOption) (*TurtleSoupRewriteScenarioResponse, error)
	TurtleSoupAnswerQuestion(ctx context.Context, in *TurtleSoupAnswerQuestionRequest, opts ...grpc.CallOption) (*TurtleSoupAnswerQuestionResponse, error)
	TurtleSoupValidateSolution(ctx context.Context, in *TurtleSoupValidateSolutionRequest, opts ...grpc.CallOption) (*TurtleSoupValidateSolutionResponse, error)
	TurtleSoupGenerateHint(ctx context.Context, in *TurtleSoupGenerateHintRequest, opts ...grpc.CallOption) (*TurtleSoupGenerateHintResponse, error)
	GetDailyUsage(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DailyUsageResponse, error)
	GetRecentUsage(ctx context.Context, in *GetRecentUsageRequest, opts ...grpc.CallOption) (*UsageListResponse, error)
	GetTotalUsage(ctx context.Context, in *GetTotalUsageRequest, opts ...grpc.CallOption) (*UsageResponse, error)
}

type lLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &lLMServiceClient{cc}
}

func (c *lLMServiceClient) GetModelConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ModelConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelConfigResponse)
	err := c.cc.Invoke(ctx, LLMService_GetModelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GuardIsMalicious(ctx context.Context, in *GuardIsMaliciousRequest, opts ...grpc.CallOption) (*GuardIsMaliciousResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuardIsMaliciousResponse)
	err := c.cc.Invoke(ctx, LLMService_GuardIsMalicious_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, LLMService_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TwentyQSelectTopic(ctx context.Context, in *TwentyQSelectTopicRequest, opts ...grpc.CallOption) (*TwentyQSelectTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwentyQSelectTopicResponse)
	err := c.cc.Invoke(ctx, LLMService_TwentyQSelectTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TwentyQGetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TwentyQGetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwentyQGetCategoriesResponse)
	err := c.cc.Invoke(ctx, LLMService_TwentyQGetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TwentyQGenerateHints(ctx context.Context, in *TwentyQGenerateHintsRequest, opts ...grpc.CallOption) (*TwentyQGenerateHintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwentyQGenerateHintsResponse)
	err := c.cc.Invoke(ctx, LLMService_TwentyQGenerateHints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TwentyQAnswerQuestion(ctx context.Context, in *TwentyQAnswerQuestionRequest, opts ...grpc.CallOption) (*TwentyQAnswerQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwentyQAnswerQuestionResponse)
	err := c.cc.Invoke(ctx, LLMService_TwentyQAnswerQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TwentyQVerifyGuess(ctx context.Context, in *TwentyQVerifyGuessRequest, opts ...grpc.CallOption) (*TwentyQVerifyGuessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwentyQVerifyGuessResponse)
	err := c.cc.Invoke(ctx, LLMService_TwentyQVerifyGuess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TwentyQNormalizeQuestion(ctx context.Context, in *TwentyQNormalizeQuestionRequest, opts ...grpc.CallOption) (*TwentyQNormalizeQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwentyQNormalizeQuestionResponse)
	err := c.cc.Invoke(ctx, LLMService_TwentyQNormalizeQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TwentyQCheckSynonym(ctx context.Context, in *TwentyQCheckSynonymRequest, opts ...grpc.CallOption) (*TwentyQCheckSynonymResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwentyQCheckSynonymResponse)
	err := c.cc.Invoke(ctx, LLMService_TwentyQCheckSynonym_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TurtleSoupGeneratePuzzle(ctx context.Context, in *TurtleSoupGeneratePuzzleRequest, opts ...grpc.CallOption) (*TurtleSoupGeneratePuzzleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurtleSoupGeneratePuzzleResponse)
	err := c.cc.Invoke(ctx, LLMService_TurtleSoupGeneratePuzzle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TurtleSoupGetRandomPuzzle(ctx context.Context, in *TurtleSoupGetRandomPuzzleRequest, opts ...grpc.CallOption) (*TurtleSoupGetRandomPuzzleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurtleSoupGetRandomPuzzleResponse)
	err := c.cc.Invoke(ctx, LLMService_TurtleSoupGetRandomPuzzle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TurtleSoupRewriteScenario(ctx context.Context, in *TurtleSoupRewriteScenarioRequest, opts ...grpc.CallOption) (*TurtleSoupRewriteScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurtleSoupRewriteScenarioResponse)
	err := c.cc.Invoke(ctx, LLMService_TurtleSoupRewriteScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TurtleSoupAnswerQuestion(ctx context.Context, in *TurtleSoupAnswerQuestionRequest, opts ...grpc.CallOption) (*TurtleSoupAnswerQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurtleSoupAnswerQuestionResponse)
	err := c.cc.Invoke(ctx, LLMService_TurtleSoupAnswerQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TurtleSoupValidateSolution(ctx context.Context, in *TurtleSoupValidateSolutionRequest, opts ...grpc.CallOption) (*TurtleSoupValidateSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurtleSoupValidateSolutionResponse)
	err := c.cc.Invoke(ctx, LLMService_TurtleSoupValidateSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TurtleSoupGenerateHint(ctx context.Context, in *TurtleSoupGenerateHintRequest, opts ...grpc.CallOption) (*TurtleSoupGenerateHintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurtleSoupGenerateHintResponse)
	err := c.cc.Invoke(ctx, LLMService_TurtleSoupGenerateHint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GetDailyUsage(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DailyUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyUsageResponse)
	err := c.cc.Invoke(ctx, LLMService_GetDailyUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GetRecentUsage(ctx context.Context, in *GetRecentUsageRequest, opts ...grpc.CallOption) (*UsageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageListResponse)
	err := c.cc.Invoke(ctx, LLMService_GetRecentUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GetTotalUsage(ctx context.Context, in *GetTotalUsageRequest, opts ...grpc.CallOption) (*UsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageResponse)
	err := c.cc.Invoke(ctx, LLMService_GetTotalUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMServiceServer is the server API for LLMService service.
// All implementations must embed UnimplementedLLMServiceServer
// for forward compatibility.
type LLMServiceServer interface {
	GetModelConfig(context.Context, *emptypb.Empty) (*ModelConfigResponse, error)
	GuardIsMalicious(context.Context, *GuardIsMaliciousRequest) (*GuardIsMaliciousResponse, error)
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	TwentyQSelectTopic(context.Context, *TwentyQSelectTopicRequest) (*TwentyQSelectTopicResponse, error)
	TwentyQGetCategories(context.Context, *emptypb.Empty) (*TwentyQGetCategoriesResponse, error)
	TwentyQGenerateHints(context.Context, *TwentyQGenerateHintsRequest) (*TwentyQGenerateHintsResponse, error)
	TwentyQAnswerQuestion(context.Context, *TwentyQAnswerQuestionRequest) (*TwentyQAnswerQuestionResponse, error)
	TwentyQVerifyGuess(context.Context, *TwentyQVerifyGuessRequest) (*TwentyQVerifyGuessResponse, error)
	TwentyQNormalizeQuestion(context.Context, *TwentyQNormalizeQuestionRequest) (*TwentyQNormalizeQuestionResponse, error)
	TwentyQCheckSynonym(context.Context, *TwentyQCheckSynonymRequest) (*TwentyQCheckSynonymResponse, error)
	TurtleSoupGeneratePuzzle(context.Context, *TurtleSoupGeneratePuzzleRequest) (*TurtleSoupGeneratePuzzleResponse, error)
	TurtleSoupGetRandomPuzzle(context.Context, *TurtleSoupGetRandomPuzzleRequest) (*TurtleSoupGetRandomPuzzleResponse, error)
	TurtleSoupRewriteScenario(context.Context, *TurtleSoupRewriteScenarioRequest) (*TurtleSoupRewriteScenarioResponse, error)
	TurtleSoupAnswerQuestion(context.Context, *TurtleSoupAnswerQuestionRequest) (*TurtleSoupAnswerQuestionResponse, error)
	TurtleSoupValidateSolution(context.Context, *TurtleSoupValidateSolutionRequest) (*TurtleSoupValidateSolutionResponse, error)
	TurtleSoupGenerateHint(context.Context, *TurtleSoupGenerateHintRequest) (*TurtleSoupGenerateHintResponse, error)
	GetDailyUsage(context.Context, *emptypb.Empty) (*DailyUsageResponse, error)
	GetRecentUsage(context.Context, *GetRecentUsageRequest) (*UsageListResponse, error)
	GetTotalUsage(context.Context, *GetTotalUsageRequest) (*UsageResponse, error)
	mustEmbedUnimplementedLLMServiceServer()
}

// UnimplementedLLMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMServiceServer struct{}

func (UnimplementedLLMServiceServer) GetModelConfig(context.Context, *emptypb.Empty) (*ModelConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelConfig not implemented")
}
func (UnimplementedLLMServiceServer) GuardIsMalicious(context.Context, *GuardIsMaliciousRequest) (*GuardIsMaliciousResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuardIsMalicious not implemented")
}
func (UnimplementedLLMServiceServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedLLMServiceServer) TwentyQSelectTopic(context.Context, *TwentyQSelectTopicRequest) (*TwentyQSelectTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwentyQSelectTopic not implemented")
}
func (UnimplementedLLMServiceServer) TwentyQGetCategories(context.Context, *emptypb.Empty) (*TwentyQGetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwentyQGetCategories not implemented")
}
func (UnimplementedLLMServiceServer) TwentyQGenerateHints(context.Context, *TwentyQGenerateHintsRequest) (*TwentyQGenerateHintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwentyQGenerateHints not implemented")
}
func (UnimplementedLLMServiceServer) TwentyQAnswerQuestion(context.Context, *TwentyQAnswerQuestionRequest) (*TwentyQAnswerQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwentyQAnswerQuestion not implemented")
}
func (UnimplementedLLMServiceServer) TwentyQVerifyGuess(context.Context, *TwentyQVerifyGuessRequest) (*TwentyQVerifyGuessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwentyQVerifyGuess not implemented")
}
func (UnimplementedLLMServiceServer) TwentyQNormalizeQuestion(context.Context, *TwentyQNormalizeQuestionRequest) (*TwentyQNormalizeQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwentyQNormalizeQuestion not implemented")
}
func (UnimplementedLLMServiceServer) TwentyQCheckSynonym(context.Context, *TwentyQCheckSynonymRequest) (*TwentyQCheckSynonymResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwentyQCheckSynonym not implemented")
}
func (UnimplementedLLMServiceServer) TurtleSoupGeneratePuzzle(context.Context, *TurtleSoupGeneratePuzzleRequest) (*TurtleSoupGeneratePuzzleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurtleSoupGeneratePuzzle not implemented")
}
func (UnimplementedLLMServiceServer) TurtleSoupGetRandomPuzzle(context.Context, *TurtleSoupGetRandomPuzzleRequest) (*TurtleSoupGetRandomPuzzleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurtleSoupGetRandomPuzzle not implemented")
}
func (UnimplementedLLMServiceServer) TurtleSoupRewriteScenario(context.Context, *TurtleSoupRewriteScenarioRequest) (*TurtleSoupRewriteScenarioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurtleSoupRewriteScenario not implemented")
}
func (UnimplementedLLMServiceServer) TurtleSoupAnswerQuestion(context.Context, *TurtleSoupAnswerQuestionRequest) (*TurtleSoupAnswerQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurtleSoupAnswerQuestion not implemented")
}
func (UnimplementedLLMServiceServer) TurtleSoupValidateSolution(context.Context, *TurtleSoupValidateSolutionRequest) (*TurtleSoupValidateSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurtleSoupValidateSolution not implemented")
}
func (UnimplementedLLMServiceServer) TurtleSoupGenerateHint(context.Context, *TurtleSoupGenerateHintRequest) (*TurtleSoupGenerateHintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TurtleSoupGenerateHint not implemented")
}
func (UnimplementedLLMServiceServer) GetDailyUsage(context.Context, *emptypb.Empty) (*DailyUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyUsage not implemented")
}
func (UnimplementedLLMServiceServer) GetRecentUsage(context.Context, *GetRecentUsageRequest) (*UsageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentUsage not implemented")
}
func (UnimplementedLLMServiceServer) GetTotalUsage(context.Context, *GetTotalUsageRequest) (*UsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalUsage not implemented")
}
func (UnimplementedLLMServiceServer) mustEmbedUnimplementedLLMServiceServer() {}
func (UnimplementedLLMServiceServer) testEmbeddedByValue()                    {}

// UnsafeLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServiceServer will
// result in compilation errors.
type UnsafeLLMServiceServer interface {
	mustEmbedUnimplementedLLMServiceServer()
}

func RegisterLLMServiceServer(s grpc.ServiceRegistrar, srv LLMServiceServer) {
	// If the following call pancis, it indicates UnimplementedLLMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMService_ServiceDesc, srv)
}

func _LLMService_GetModelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetModelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetModelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetModelConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GuardIsMalicious_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuardIsMaliciousRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GuardIsMalicious(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GuardIsMalicious_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GuardIsMalicious(ctx, req.(*GuardIsMaliciousRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TwentyQSelectTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwentyQSelectTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TwentyQSelectTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TwentyQSelectTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TwentyQSelectTopic(ctx, req.(*TwentyQSelectTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TwentyQGetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TwentyQGetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TwentyQGetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TwentyQGetCategories(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TwentyQGenerateHints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwentyQGenerateHintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TwentyQGenerateHints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TwentyQGenerateHints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TwentyQGenerateHints(ctx, req.(*TwentyQGenerateHintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TwentyQAnswerQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwentyQAnswerQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TwentyQAnswerQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TwentyQAnswerQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TwentyQAnswerQuestion(ctx, req.(*TwentyQAnswerQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TwentyQVerifyGuess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwentyQVerifyGuessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TwentyQVerifyGuess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TwentyQVerifyGuess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TwentyQVerifyGuess(ctx, req.(*TwentyQVerifyGuessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TwentyQNormalizeQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwentyQNormalizeQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TwentyQNormalizeQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TwentyQNormalizeQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TwentyQNormalizeQuestion(ctx, req.(*TwentyQNormalizeQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TwentyQCheckSynonym_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwentyQCheckSynonymRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TwentyQCheckSynonym(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TwentyQCheckSynonym_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TwentyQCheckSynonym(ctx, req.(*TwentyQCheckSynonymRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TurtleSoupGeneratePuzzle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurtleSoupGeneratePuzzleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TurtleSoupGeneratePuzzle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TurtleSoupGeneratePuzzle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TurtleSoupGeneratePuzzle(ctx, req.(*TurtleSoupGeneratePuzzleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TurtleSoupGetRandomPuzzle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurtleSoupGetRandomPuzzleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TurtleSoupGetRandomPuzzle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TurtleSoupGetRandomPuzzle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TurtleSoupGetRandomPuzzle(ctx, req.(*TurtleSoupGetRandomPuzzleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TurtleSoupRewriteScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurtleSoupRewriteScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TurtleSoupRewriteScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TurtleSoupRewriteScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TurtleSoupRewriteScenario(ctx, req.(*TurtleSoupRewriteScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TurtleSoupAnswerQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurtleSoupAnswerQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TurtleSoupAnswerQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TurtleSoupAnswerQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TurtleSoupAnswerQuestion(ctx, req.(*TurtleSoupAnswerQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TurtleSoupValidateSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurtleSoupValidateSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TurtleSoupValidateSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TurtleSoupValidateSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TurtleSoupValidateSolution(ctx, req.(*TurtleSoupValidateSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TurtleSoupGenerateHint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurtleSoupGenerateHintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TurtleSoupGenerateHint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TurtleSoupGenerateHint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TurtleSoupGenerateHint(ctx, req.(*TurtleSoupGenerateHintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GetDailyUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetDailyUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetDailyUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetDailyUsage(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GetRecentUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetRecentUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetRecentUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetRecentUsage(ctx, req.(*GetRecentUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GetTotalUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetTotalUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetTotalUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetTotalUsage(ctx, req.(*GetTotalUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMService_ServiceDesc is the grpc.ServiceDesc for LLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.v1.LLMService",
	HandlerType: (*LLMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModelConfig",
			Handler:    _LLMService_GetModelConfig_Handler,
		},
		{
			MethodName: "GuardIsMalicious",
			Handler:    _LLMService_GuardIsMalicious_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _LLMService_EndSession_Handler,
		},
		{
			MethodName: "TwentyQSelectTopic",
			Handler:    _LLMService_TwentyQSelectTopic_Handler,
		},
		{
			MethodName: "TwentyQGetCategories",
			Handler:    _LLMService_TwentyQGetCategories_Handler,
		},
		{
			MethodName: "TwentyQGenerateHints",
			Handler:    _LLMService_TwentyQGenerateHints_Handler,
		},
		{
			MethodName: "TwentyQAnswerQuestion",
			Handler:    _LLMService_TwentyQAnswerQuestion_Handler,
		},
		{
			MethodName: "TwentyQVerifyGuess",
			Handler:    _LLMService_TwentyQVerifyGuess_Handler,
		},
		{
			MethodName: "TwentyQNormalizeQuestion",
			Handler:    _LLMService_TwentyQNormalizeQuestion_Handler,
		},
		{
			MethodName: "TwentyQCheckSynonym",
			Handler:    _LLMService_TwentyQCheckSynonym_Handler,
		},
		{
			MethodName: "TurtleSoupGeneratePuzzle",
			Handler:    _LLMService_TurtleSoupGeneratePuzzle_Handler,
		},
		{
			MethodName: "TurtleSoupGetRandomPuzzle",
			Handler:    _LLMService_TurtleSoupGetRandomPuzzle_Handler,
		},
		{
			MethodName: "TurtleSoupRewriteScenario",
			Handler:    _LLMService_TurtleSoupRewriteScenario_Handler,
		},
		{
			MethodName: "TurtleSoupAnswerQuestion",
			Handler:    _LLMService_TurtleSoupAnswerQuestion_Handler,
		},
		{
			MethodName: "TurtleSoupValidateSolution",
			Handler:    _LLMService_TurtleSoupValidateSolution_Handler,
		},
		{
			MethodName: "TurtleSoupGenerateHint",
			Handler:    _LLMService_TurtleSoupGenerateHint_Handler,
		},
		{
			MethodName: "GetDailyUsage",
			Handler:    _LLMService_GetDailyUsage_Handler,
		},
		{
			MethodName: "GetRecentUsage",
			Handler:    _LLMService_GetRecentUsage_Handler,
		},
		{
			MethodName: "GetTotalUsage",
			Handler:    _LLMService_GetTotalUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm/v1/llm_service.proto",
}
