# syntax=docker/dockerfile:1.7

FROM eclipse-temurin:25-jdk
WORKDIR /app

ENV ORG_GRADLE_JAVA_HOME=/opt/java/openjdk \
    GRADLE_OPTS="-Dorg.gradle.java.home=/opt/java/openjdk"

COPY gradlew ./
COPY gradle ./gradle
COPY settings.gradle.kts build.gradle.kts gradle.properties ./

RUN chmod +x gradlew && \
    ./gradlew --no-daemon dependencies || true

EXPOSE 40257

CMD ["./gradlew","run","--continuous","--no-daemon"]
