// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/config"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/domain/turtlesoup"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/domain/twentyq"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/gemini"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/guard"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/handler"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/metrics"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/server"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/session"
	"github.com/park285/llm-kakao-bots/mcp-llm-server-go/internal/usage"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	store := metrics.NewStore()
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	repository := usage.NewRepository(configConfig, logger)
	recorder := usage.NewRecorder(configConfig, repository, logger)
	client, err := gemini.NewClient(configConfig, store, recorder)
	if err != nil {
		return nil, err
	}
	injectionGuard, err := guard.NewGuard(configConfig, logger)
	if err != nil {
		return nil, err
	}
	llmHandler := handler.NewLLMHandler(configConfig, client, injectionGuard, store, repository, logger)
	sessionStore, err := session.NewStore(configConfig)
	if err != nil {
		return nil, err
	}
	manager := session.NewManager(sessionStore, client, configConfig, logger)
	sessionHandler := handler.NewSessionHandler(manager, injectionGuard, logger)
	guardHandler := handler.NewGuardHandler(injectionGuard)
	usageHandler := handler.NewUsageHandler(configConfig, repository, logger)
	prompts, err := twentyq.NewPrompts()
	if err != nil {
		return nil, err
	}
	twentyQHandler := handler.NewTwentyQHandler(configConfig, client, injectionGuard, sessionStore, prompts, logger)
	turtlesoupPrompts, err := turtlesoup.NewPrompts()
	if err != nil {
		return nil, err
	}
	puzzleLoader, err := turtlesoup.NewPuzzleLoader()
	if err != nil {
		return nil, err
	}
	turtleSoupHandler := handler.NewTurtleSoupHandler(configConfig, client, injectionGuard, sessionStore, turtlesoupPrompts, puzzleLoader, logger)
	engine := handler.NewRouter(configConfig, logger, llmHandler, sessionHandler, guardHandler, usageHandler, twentyQHandler, turtleSoupHandler)
	httpServer := server.NewHTTPServer(configConfig, engine)
	app := NewApp(httpServer, logger, configConfig, sessionStore, repository, recorder)
	return app, nil
}
