// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"log/slog"

	"github.com/park285/llm-kakao-bots/game-bot-go/internal/common/bootstrap"
	"github.com/park285/llm-kakao-bots/game-bot-go/internal/twentyq/config"
)

// Injectors from wire.go:

//go:generate go run github.com/google/wire/cmd/wire@v0.7.0
func Initialize(ctx context.Context, cfg *config.Config, logger *slog.Logger) (*bootstrap.ServerApp, func(), error) {
	client, err := newTwentyQRestClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	provider, err := newTwentyQMessageProvider()
	if err != nil {
		return nil, nil, err
	}
	dataValkeyClient, cleanup, err := newTwentyQDataRedis(ctx, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	appTwentyQStores := newTwentyQStores(dataValkeyClient, logger)
	db, cleanup2, err := newTwentyQDB(ctx, cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repository, err := newTwentyQRepository(ctx, db)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	statsRecorder, cleanup3 := newTwentyQStatsRecorder(cfg, repository, logger)
	riddleService := newTwentyQRiddleService(cfg, client, provider, appTwentyQStores, statsRecorder, logger)
	serveMux := newTwentyQHTTPMux(riddleService, db, provider, logger)
	server := newTwentyQHTTPServer(cfg, serveMux)
	mqValkeyClient, cleanup4, err := newTwentyQMQValkey(ctx, cfg, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appTwentyQAdminServices := newTwentyQAdminServices(cfg, db, client, provider, appTwentyQStores, riddleService, logger)
	appTwentyQMQPipeline := newTwentyQMQPipeline(cfg, mqValkeyClient, client, provider, appTwentyQStores, riddleService, appTwentyQAdminServices, logger)
	serverApp := newTwentyQServerApp(logger, server, appTwentyQMQPipeline)
	return serverApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
