// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"llm-watchdog/watchdog"
	"log/slog"
)

// Injectors from wire.go:

func initializeWatchdogRuntime(cfg watchdog.Config, meta WatchdogConfigMeta, logger *slog.Logger) (*WatchdogRuntime, error) {
	string2 := newDockerHost(cfg)
	client, err := newDockerClient(string2)
	if err != nil {
		return nil, err
	}
	watchdogWatchdog := newWatchdog(client, cfg, meta, logger)
	watchdogRuntime := &WatchdogRuntime{
		DockerHost:   string2,
		DockerClient: client,
		Watchdog:     watchdogWatchdog,
	}
	return watchdogRuntime, nil
}
